// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQQBuTfMsNnBBLUrWyOZIUsgAMzniD0MM',
    appId: '1:483356747005:android:f0badbf2b85766a77bca94',
    messagingSenderId: '483356747005',
    projectId: 'vpn-proxy-864ba',
    databaseURL: 'https://vpn-proxy-864ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vpn-proxy-864ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVlBmsuicsGEPNZQoWIJYxCO2I5tPZ18',
    appId: '1:483356747005:ios:ae62e34500bcd5ee7bca94',
    messagingSenderId: '483356747005',
    projectId: 'vpn-proxy-864ba',
    databaseURL: 'https://vpn-proxy-864ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vpn-proxy-864ba.appspot.com',
    androidClientId: '483356747005-30qv8u9vjeicoumqagbh8s2msfu8hjp2.apps.googleusercontent.com',
    iosClientId: '483356747005-b7nnu4f5ud9d2mnr34jq2m23q7hklsdd.apps.googleusercontent.com',
    iosBundleId: 'com.papa.vpn',
  );
}
